### ISSUE TITLE
Use String.to_existing_atom to avoid leaking.

### ISSUE THREAD

**Issue by vic** [sheharyarn/better_params#1]
A quick look at your code, seems like using your ExUtils to convert any request parameter into atoms is a bad idea (unless you used something like String.to_existing_atom), otherwise it would be really easy to create something that generates random parameter keys and quickly fills your atom table as they are never freed.

**Comment by sheharyarn** [comment]
Nice catch. I'll update the code to use `String.to_existing_atom`. Thanks!

**Comment by sheharyarn** [comment]
Version `0.2` published with the changes. I can't believe this slipped my mind, I had been using this on a production app for about two months before publishing it as a package. Also mentioned this in the [Readme](https://github.com/sheharyarn/better_params#notes), to not scare off other devs. 😛

Thanks for pointing this out again. 😄
